### ISSUE TITLE
Could I use this with Meteor 1.3?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-flow-router-title#1]
Could I use this with Meteor 1.3?
Please help me.

**Comment by dr-dimitru** [comment]
This package wasn't tested with Meteor 1.3, yet.
But I don't see any limitations here. If you have ability to test it with 1.3, - I'll be very appreciated.

**Comment by thearabbit** [comment]
Now it work fine

``` js
import {FlowRouterTitle} from 'meteor/ostrio:flow-router-title';

new FlowRouterTitle(FlowRouter);
```
