### ISSUE TITLE
FlowRouterTitle undefined

### ISSUE THREAD

**Issue by GiordanoArman** [VeliovGroup/Meteor-flow-router-title#3]
This is what I get after meteor add <package> and using "new FlowRouterTitle" after I have created all the routes. Any idea why? Maybe I am doing something wrong? I am declaring all the routes in a jsx file.

W20160423-23:58:04.011(2)? (STDERR)  
W20160423-23:58:04.012(2)? (STDERR) /home/giordano/.meteor/packages/meteor-tool/.1.3.0_3.a5p6a8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160423-23:58:04.013(2)? (STDERR)                     throw(ex);
W20160423-23:58:04.013(2)? (STDERR)                           ^
W20160423-23:58:04.196(2)? (STDERR) ReferenceError: FlowRouterTitle is not defined
W20160423-23:58:04.197(2)? (STDERR)     at meteorInstall.app.routes.jsx (app/routes.jsx:80:5)
W20160423-23:58:04.197(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160423-23:58:04.198(2)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160423-23:58:04.198(2)? (STDERR)     at /home/giordano/git/shopluxurystyles/.meteor/local/build/programs/server/app/app.js:4092:1
W20160423-23:58:04.198(2)? (STDERR)     at /home/giordano/git/shopluxurystyles/.meteor/local/build/programs/server/boot.js:283:10
W20160423-23:58:04.199(2)? (STDERR)     at Array.forEach (native)
W20160423-23:58:04.199(2)? (STDERR)     at Function._.each._.forEach (/home/giordano/.meteor/packages/meteor-tool/.1.3.0_3.a5p6a8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160423-23:58:04.199(2)? (STDERR)     at /home/giordano/git/shopluxurystyles/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8

**Comment by dr-dimitru** [comment]
Hi @GiordanoArman 

You're trying to call this on server's side, but this package is client only

**Comment by dr-dimitru** [comment]
Hi @GiordanoArman any news on your end?

**Comment by GiordanoArman** [comment]
@dr-dimitru hey, hi! I just changed the way I was doing things (:

**Comment by dr-dimitru** [comment]
I guess, we can close this issue?

**Comment by GiordanoArman** [comment]
@dr-dimitru yes, sorry for not reaching back, I just forgot about it.
