### ISSUE TITLE
Title don't reactive with TAPi18n?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-flow-router-title#4]
Title don't reactive

``` js
title: function () {
        return TAPi18n.__('core.exchange.title');
    },
```

I try to change language in the same route, it don't reactive.

**Comment by dr-dimitru** [comment]
Returned value from this `Function` must be reactive (_if you want to have it reactive_)
1. What is returned by `TAPi18n.__()` method?
2. What do you actually expect?
3. How you change the title? (_I guess you trying to change title outside of the Router, right?_)

**Comment by dr-dimitru** [comment]
Just to make sure you use this lib with [flow-router-extra](https://github.com/VeliovGroup/flow-router), right?

**Comment by dr-dimitru** [comment]
@thearabbit any news on your end?

**Comment by thearabbit** [comment]
Sorry I am late, It work fine.
