### ISSUE TITLE
Duplicate ReactiveDict name: activeRouteConfig

### ISSUE THREAD

**Issue by wiiiimm** [VeliovGroup/Meteor-flow-router-title#8]
Meteor version 1.4.4.1

Duplicate ReactiveDict name: activeRouteConfig error begins to show as soon as Meteor flow router title was added with `meteor add ostrio:flow-router-title` (even without any code level changes).

Plugin still seems to work once the required code is added in FlowRouter routes, the error still persists.

![screen shot 2017-06-07 at 17 46 50](https://user-images.githubusercontent.com/179761/26872516-5f971f98-4ba9-11e7-8c4b-0f5c735ae008.png)

**Comment by dr-dimitru** [comment]
Hello @williamli ,

I can not reproduce it. Could you please post your `.meteor/packages` file?

**Comment by wiiiimm** [comment]
### just upgraded to Meteor version 1.5




```
meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.18                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
session@1.1.7                 # Client-side reactive dictionary for your app
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.8.0              # Enable ECMAScript2015+ syntax in app code

kadira:flow-router
kadira:blaze-layout
alanning:roles
accounts-password@1.3.6
arillo:flow-router-helpers
accounts-base@1.3.0
mantarayar:shortid
momentjs:moment
check@1.2.5
random@1.0.10
wylio:mandrill
themeteorchef:jquery-validation
lbee:moment-helpers
risul:moment-timezone
yagni:split-on-newlines
reactive-dict@1.1.9
juliancwirko:s-alert
juliancwirko:s-alert-stackslide
patrickml:swal
risul:jsondiffpatch
maximdubrovin:uploadcare


http@1.2.12
fortawesome:fontawesome
lukemadera:social-share
tomwasd:flow-router-seo
maxharris9:classnames
underscorestring:underscore.string
djedi:sanitize-html-client
raix:handlebar-helpers


reywood:publish-composite
standard-minifier-css@1.3.4
standard-minifier-js@2.1.0
shell-server@0.2.3
react-template-helper
react-meteor-data
fourseven:scss
email@1.2.1
dynamic-import
```

**Comment by dr-dimitru** [comment]
Hello @williamli ,
Thanks for info.

 1. I don't see `ostrio:flow-router-title` to be installed
 2. `ostrio:flow-router-title` is guaranteed to work only with [`ostrio:flow-router-extra`](https://github.com/VeliovGroup/flow-router)
 3. If you swap `kadira:flow-router` with `meteor/ostrio:flow-router-extra`, do not forget to remove `arillo:flow-router-helpers` (it's built in)

**Comment by wiiiimm** [comment]
1. `ostrio:flow-router-title` is not installed because it was causing the problem
2. i didn't know i need to use `ostrio:flow-router-extra` instead of `kadira:flow-router`

thanks for the info.

ps: maybe a line stating it is not intended for `kadira:flow-router` in the README would help?

**Comment by dr-dimitru** [comment]
See second line - https://github.com/VeliovGroup/Meteor-flow-router-title#reactive-page-title

**Comment by dr-dimitru** [comment]
BTW FlowRouter-Extra already suggested by [blaze.js](http://blazejs.org/guide/routing.html#Flow-Router-Extra) and it's coming to [Meteor's guide](https://github.com/meteor/guide/pull/640)
